import { ThreatActor } from '../types.js';

export const SYNTHETIC_ACTORS: ThreatActor[] = [
  {
    id: 'ACTOR-DEMO-001',
    alias: 'ShadowX',
    primaryHandle: 'ShadowX',
    alternateHandles: ['Shadow_X01', 'XShadow', 'ShadowOperator'],
    category: 'Cybercrime',
    firstSeen: '2025-02-14',
    lastSeen: '2026-08-21',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 84,
    summary: 'High-volume underground broker selling specialized corporate access keys and database credentials across dark web forums.',
    linkedIdentifiersCount: 7,
    relationshipsCount: 14,
    observationsCount: 28,
    primaryLanguages: ['English', 'Russian'],
    knownPlatforms: ['Synthetic Forum Alpha', 'Synthetic Market Omega', 'CryptID Escrow Hub'],
    riskRating: 'Critical'
  },
  {
    id: 'ACTOR-DEMO-002',
    alias: 'NightCipher',
    primaryHandle: 'NightCipher',
    alternateHandles: ['CipherNight_24', 'NC_Dev'],
    category: 'Data Extortion',
    firstSeen: '2025-03-01',
    lastSeen: '2026-08-14',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 68,
    summary: 'Extortion affiliate specializing in exfiltrated healthcare and financial CRM archives.',
    linkedIdentifiersCount: 5,
    relationshipsCount: 9,
    observationsCount: 19,
    primaryLanguages: ['English'],
    knownPlatforms: ['Synthetic Forum Alpha', 'LeakMarket Demo'],
    riskRating: 'High'
  },
  {
    id: 'ACTOR-DEMO-003',
    alias: 'GhostByte',
    primaryHandle: 'GhostByte',
    alternateHandles: ['Ghost_B8', 'ByteGhost99'],
    category: 'Financial Fraud',
    firstSeen: '2025-01-20',
    lastSeen: '2026-09-02',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 79,
    summary: 'Laundering operative coordinating cryptocurrency tumbling and multi-hop token mixers with connected escrow accounts.',
    linkedIdentifiersCount: 6,
    relationshipsCount: 11,
    observationsCount: 22,
    primaryLanguages: ['English', 'German'],
    knownPlatforms: ['Synthetic Market Omega', 'MixerPool Demo'],
    riskRating: 'High'
  },
  {
    id: 'ACTOR-DEMO-004',
    alias: 'DarkOrbit',
    primaryHandle: 'DarkOrbit',
    alternateHandles: ['OrbitDark', 'D_Orbit_V'],
    category: 'Malware Distribution',
    firstSeen: '2025-04-10',
    lastSeen: '2026-07-30',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 65,
    summary: 'Distributor of infostealer payloads via deceptive SEO poisoning and spoofed utility utilities.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 8,
    observationsCount: 16,
    primaryLanguages: ['Russian', 'English'],
    knownPlatforms: ['Synthetic Forum Beta', 'MalShare Demo Hub'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-005',
    alias: 'RavenNode',
    primaryHandle: 'RavenNode',
    alternateHandles: ['Raven_Ops', 'CorvusNode'],
    category: 'Access Broker',
    firstSeen: '2025-05-18',
    lastSeen: '2026-09-12',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 82,
    summary: 'Initial access broker specializing in compromised VPN gateways and remote desktop protocol endpoints.',
    linkedIdentifiersCount: 5,
    relationshipsCount: 10,
    observationsCount: 20,
    primaryLanguages: ['English', 'Spanish'],
    knownPlatforms: ['Synthetic Forum Alpha', 'EnterpriseAccess Demo'],
    riskRating: 'Critical'
  },
  {
    id: 'ACTOR-DEMO-006',
    alias: 'ZeroTrace',
    primaryHandle: 'ZeroTrace',
    alternateHandles: ['ZT_Anonymous', 'TraceZero_0'],
    category: 'Stealth Operation',
    firstSeen: '2025-06-01',
    lastSeen: '2026-08-05',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Low',
    confidenceScore: 42,
    summary: 'Highly compartmentalized persona utilizing ephemeral disposable credentials with minimal operational trail.',
    linkedIdentifiersCount: 3,
    relationshipsCount: 5,
    observationsCount: 11,
    primaryLanguages: ['English'],
    knownPlatforms: ['OnionDrop Demo'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-007',
    alias: 'PhantomRoot',
    primaryHandle: 'PhantomRoot',
    alternateHandles: ['RootPhantom_X', 'PRoot'],
    category: 'Cybercrime',
    firstSeen: '2025-02-28',
    lastSeen: '2026-07-19',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 71,
    summary: 'Rootkit designer offering covert persistence modules for compromised Linux server farms.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 7,
    observationsCount: 15,
    primaryLanguages: ['English', 'Chinese'],
    knownPlatforms: ['Synthetic Forum Beta'],
    riskRating: 'High'
  },
  {
    id: 'ACTOR-DEMO-008',
    alias: 'SilentVector',
    primaryHandle: 'SilentVector',
    alternateHandles: ['SV_Payload', 'VectorSilent'],
    category: 'Malware Distribution',
    firstSeen: '2025-07-04',
    lastSeen: '2026-09-18',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 77,
    summary: 'Command-and-control infrastructure operator managing rotating DNS fast-flux networks.',
    linkedIdentifiersCount: 5,
    relationshipsCount: 9,
    observationsCount: 18,
    primaryLanguages: ['English'],
    knownPlatforms: ['Synthetic Market Omega', 'BotMaster Demo'],
    riskRating: 'High'
  },
  {
    id: 'ACTOR-DEMO-009',
    alias: 'CobaltWeaver',
    primaryHandle: 'CobaltWeaver',
    alternateHandles: ['CW_Strike', 'WeaverCobalt'],
    category: 'Cybercrime',
    firstSeen: '2025-03-15',
    lastSeen: '2026-08-29',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 86,
    summary: 'Custom beacon profiler customizing evasive Cobalt Strike malleable C2 configurations.',
    linkedIdentifiersCount: 6,
    relationshipsCount: 12,
    observationsCount: 24,
    primaryLanguages: ['English', 'Russian'],
    knownPlatforms: ['Synthetic Forum Alpha', 'BeaconMarket Demo'],
    riskRating: 'Critical'
  },
  {
    id: 'ACTOR-DEMO-010',
    alias: 'KryptonGhost',
    primaryHandle: 'KryptonGhost',
    alternateHandles: ['KGhost_Sec', 'Krypton_9'],
    category: 'Financial Fraud',
    firstSeen: '2025-08-11',
    lastSeen: '2026-06-25',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 59,
    summary: 'Specialist in automated carding scripts and stolen point-of-sale terminal dump validation.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 6,
    observationsCount: 14,
    primaryLanguages: ['English'],
    knownPlatforms: ['Synthetic Market Omega'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-011',
    alias: 'ViperLoom',
    primaryHandle: 'ViperLoom',
    alternateHandles: ['Viper_Loom', 'VL_Ops'],
    category: 'Ransomware Broker',
    firstSeen: '2025-04-22',
    lastSeen: '2026-09-08',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 88,
    summary: 'Negotiator and ransom payment intermediary coordinating double-extortion victim portals.',
    linkedIdentifiersCount: 7,
    relationshipsCount: 13,
    observationsCount: 27,
    primaryLanguages: ['English', 'Russian'],
    knownPlatforms: ['Synthetic Forum Alpha', 'RansomPortal Demo'],
    riskRating: 'Critical'
  },
  {
    id: 'ACTOR-DEMO-012',
    alias: 'OnyxReaper',
    primaryHandle: 'OnyxReaper',
    alternateHandles: ['ReaperOnyx', 'Onyx_R'],
    category: 'Data Extortion',
    firstSeen: '2025-05-09',
    lastSeen: '2026-08-30',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 63,
    summary: 'Leaker targeting manufacturing blueprint repositories and intellectual property dumps.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 7,
    observationsCount: 15,
    primaryLanguages: ['English'],
    knownPlatforms: ['LeakMarket Demo'],
    riskRating: 'High'
  },
  {
    id: 'ACTOR-DEMO-013',
    alias: 'AegisNull',
    primaryHandle: 'AegisNull',
    alternateHandles: ['NullAegis', 'Aegis_0'],
    category: 'Stealth Operation',
    firstSeen: '2025-09-01',
    lastSeen: '2026-09-20',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Low',
    confidenceScore: 48,
    summary: 'Anonymity enthusiast testing bulletproof proxy chaining mechanisms across offshore autonomous systems.',
    linkedIdentifiersCount: 3,
    relationshipsCount: 5,
    observationsCount: 12,
    primaryLanguages: ['English', 'German'],
    knownPlatforms: ['Synthetic Forum Beta'],
    riskRating: 'Low'
  },
  {
    id: 'ACTOR-DEMO-014',
    alias: 'FrostByte',
    primaryHandle: 'FrostByte',
    alternateHandles: ['Byte_Frost', 'FB_Zero'],
    category: 'Malware Distribution',
    firstSeen: '2025-06-17',
    lastSeen: '2026-07-28',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 67,
    summary: 'Loader operator renting malware dropper slots on spam campaigns targeting municipal utilities.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 8,
    observationsCount: 16,
    primaryLanguages: ['English'],
    knownPlatforms: ['BotMaster Demo'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-015',
    alias: 'IronSpecter',
    primaryHandle: 'IronSpecter',
    alternateHandles: ['SpecterIron', 'IS_Ghost'],
    category: 'Access Broker',
    firstSeen: '2025-01-15',
    lastSeen: '2026-09-14',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 81,
    summary: 'Distributes compromised single sign-on tokens gathered from session hijacking infostealer logs.',
    linkedIdentifiersCount: 5,
    relationshipsCount: 10,
    observationsCount: 21,
    primaryLanguages: ['English', 'Russian'],
    knownPlatforms: ['Synthetic Forum Alpha', 'EnterpriseAccess Demo'],
    riskRating: 'Critical'
  },
  {
    id: 'ACTOR-DEMO-016',
    alias: 'NexusDrift',
    primaryHandle: 'NexusDrift',
    alternateHandles: ['DriftNexus', 'N_Drift'],
    category: 'Financial Fraud',
    firstSeen: '2025-07-21',
    lastSeen: '2026-08-11',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 61,
    summary: 'Synthesizes synthetic credit profiles using cross-matched social security and consumer report leaks.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 6,
    observationsCount: 13,
    primaryLanguages: ['English'],
    knownPlatforms: ['Synthetic Market Omega'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-017',
    alias: 'PulseFiend',
    primaryHandle: 'PulseFiend',
    alternateHandles: ['PF_Pulse', 'FiendPulse'],
    category: 'Cybercrime',
    firstSeen: '2025-08-04',
    lastSeen: '2026-09-01',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Low',
    confidenceScore: 49,
    summary: 'DDoS-for-hire stresser booter service operator targeting e-commerce merchant during promotional peaks.',
    linkedIdentifiersCount: 3,
    relationshipsCount: 5,
    observationsCount: 10,
    primaryLanguages: ['English'],
    knownPlatforms: ['Synthetic Forum Beta'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-018',
    alias: 'CrimsonHelix',
    primaryHandle: 'CrimsonHelix',
    alternateHandles: ['HelixCrimson', 'CH_Sec'],
    category: 'Ransomware Broker',
    firstSeen: '2025-03-12',
    lastSeen: '2026-09-15',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 85,
    summary: 'Affiliate manager operating dedicated decryption key testing suites and victim escrow accounts.',
    linkedIdentifiersCount: 6,
    relationshipsCount: 11,
    observationsCount: 23,
    primaryLanguages: ['English', 'Russian'],
    knownPlatforms: ['Synthetic Forum Alpha', 'RansomPortal Demo'],
    riskRating: 'Critical'
  },
  {
    id: 'ACTOR-DEMO-019',
    alias: 'VoidStrider',
    primaryHandle: 'VoidStrider',
    alternateHandles: ['StriderVoid', 'Void_S'],
    category: 'Stealth Operation',
    firstSeen: '2025-10-05',
    lastSeen: '2026-08-17',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Low',
    confidenceScore: 44,
    summary: 'Uses nested Tor over VPN hops to post anonymous security audits of other underground forum scripts.',
    linkedIdentifiersCount: 3,
    relationshipsCount: 4,
    observationsCount: 9,
    primaryLanguages: ['English'],
    knownPlatforms: ['Synthetic Forum Beta'],
    riskRating: 'Low'
  },
  {
    id: 'ACTOR-DEMO-020',
    alias: 'TitanForge',
    primaryHandle: 'TitanForge',
    alternateHandles: ['TF_Exploit', 'Titan_Forge'],
    category: 'Access Broker',
    firstSeen: '2025-02-18',
    lastSeen: '2026-09-22',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 89,
    summary: 'Senior underground exploit broker facilitating zero-day and n-day proof of concept trade.',
    linkedIdentifiersCount: 6,
    relationshipsCount: 12,
    observationsCount: 25,
    primaryLanguages: ['English', 'Russian'],
    knownPlatforms: ['Synthetic Forum Alpha', 'EnterpriseAccess Demo'],
    riskRating: 'Critical'
  },
  {
    id: 'ACTOR-DEMO-021',
    alias: 'EchoBane',
    primaryHandle: 'EchoBane',
    alternateHandles: ['BaneEcho', 'EB_Bane'],
    category: 'Data Extortion',
    firstSeen: '2025-06-29',
    lastSeen: '2026-07-15',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 58,
    summary: 'Aggregates breach archives and provides cross-referenced query lookups on synthetic leak aggregators.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 6,
    observationsCount: 13,
    primaryLanguages: ['English'],
    knownPlatforms: ['LeakMarket Demo'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-022',
    alias: 'SolarFlare_X',
    primaryHandle: 'SolarFlare_X',
    alternateHandles: ['SF_Flare', 'Solar_X'],
    category: 'Malware Distribution',
    firstSeen: '2025-05-30',
    lastSeen: '2026-08-25',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 64,
    summary: 'Operates automated traffic direction systems (TDS) delivering banking Trojans across regional banks.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 7,
    observationsCount: 14,
    primaryLanguages: ['English', 'Spanish'],
    knownPlatforms: ['Synthetic Market Omega'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-023',
    alias: 'NebulaShroud',
    primaryHandle: 'NebulaShroud',
    alternateHandles: ['ShroudNebula', 'NS_Ghost'],
    category: 'Stealth Operation',
    firstSeen: '2025-07-19',
    lastSeen: '2026-09-09',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'Medium',
    confidenceScore: 56,
    summary: 'Specialist in covert domain generation algorithms (DGA) and decentralized name service lookups.',
    linkedIdentifiersCount: 4,
    relationshipsCount: 6,
    observationsCount: 12,
    primaryLanguages: ['English'],
    knownPlatforms: ['Synthetic Forum Beta'],
    riskRating: 'Moderate'
  },
  {
    id: 'ACTOR-DEMO-024',
    alias: 'QuasarLock',
    primaryHandle: 'QuasarLock',
    alternateHandles: ['LockQuasar', 'QL_Admin'],
    category: 'Ransomware Broker',
    firstSeen: '2025-04-03',
    lastSeen: '2026-09-24',
    status: 'Synthetic Demo Profile',
    confidenceLevel: 'High',
    confidenceScore: 83,
    summary: 'Affiliate operator managing payload encryption pipelines and automated ransom proof-of-decryption portals.',
    linkedIdentifiersCount: 5,
    relationshipsCount: 10,
    observationsCount: 22,
    primaryLanguages: ['English', 'Russian'],
    knownPlatforms: ['Synthetic Forum Alpha', 'RansomPortal Demo'],
    riskRating: 'Critical'
  }
];
