import { SourceRecord, TimelineEvent, RelationshipRecord, ObservationRecord } from '../types.js';

export const SYNTHETIC_SOURCES: SourceRecord[] = [
  { id: 'SOURCE-DEMO-001', name: 'Synthetic Forum Alpha', type: 'Synthetic Forum', reliability: 'A (High)', observationsCount: 84, firstIngested: '2025-01-10', lastIngested: '2026-09-25', urlSample: 'http://synthforumalpha9924.onion/board', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-002', name: 'Synthetic Market Omega', type: 'Synthetic Marketplace', reliability: 'A (High)', observationsCount: 68, firstIngested: '2025-01-15', lastIngested: '2026-09-24', urlSample: 'http://synthmarketomega77.onion/vendor/catalog', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-003', name: 'Synthetic Forum Beta', type: 'Synthetic Forum', reliability: 'B (Moderate)', observationsCount: 42, firstIngested: '2025-02-01', lastIngested: '2026-09-18', urlSample: 'http://synthforumbeta88.onion/threads', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-004', name: 'LeakMarket Demo Archive', type: 'Synthetic Marketplace', reliability: 'B (Moderate)', observationsCount: 39, firstIngested: '2025-02-15', lastIngested: '2026-09-12', urlSample: 'http://leakmarketdemo99archive.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-005', name: 'BotMaster Demo Network', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 31, firstIngested: '2025-03-01', lastIngested: '2026-09-15', urlSample: 'http://botmasterfeeddemo.onion/c2', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-006', name: 'OnionDrop Demo Paste', type: 'Synthetic Forum', reliability: 'C (Low)', observationsCount: 22, firstIngested: '2025-03-10', lastIngested: '2026-08-20', urlSample: 'http://oniondropdemopaste44.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-007', name: 'Blockchain Cluster Synthetic Index', type: 'Synthetic Blockchain Cluster', reliability: 'A (High)', observationsCount: 56, firstIngested: '2025-01-05', lastIngested: '2026-09-26', urlSample: 'https://demo-intel-ledger.internal/clusters', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-008', name: 'ThreatInfra Synthetic Telemetry', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 64, firstIngested: '2025-01-08', lastIngested: '2026-09-25', urlSample: 'https://demo-intel-infra.internal/dns-passive', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-009', name: 'Synthetic CertStream Monitor', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 36, firstIngested: '2025-02-01', lastIngested: '2026-09-22', urlSample: 'https://demo-intel-certs.internal/stream', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-010', name: 'Public Threat Report - CISA Alert 2025-Demo', type: 'Public Threat Report', reliability: 'A (High)', observationsCount: 18, firstIngested: '2025-04-14', lastIngested: '2025-11-20', urlSample: 'https://www.cisa.gov/news-events/cybersecurity-advisories/aa25-synthetic-demo', isSynthetic: false, collectorMethod: 'Public Advisory Mirror' },
  { id: 'SOURCE-DEMO-011', name: 'Public Threat Report - ENISA Threat Landscape 2025-Demo', type: 'Public Threat Report', reliability: 'A (High)', observationsCount: 15, firstIngested: '2025-05-10', lastIngested: '2025-12-05', urlSample: 'https://www.enisa.europa.eu/publications/etl-synthetic-demo-2025', isSynthetic: false, collectorMethod: 'Public Advisory Mirror' },
  { id: 'SOURCE-DEMO-012', name: 'Synthetic Tor Node Consensus', type: 'Synthetic Intelligence Feed', reliability: 'B (Moderate)', observationsCount: 29, firstIngested: '2025-01-12', lastIngested: '2026-09-10', urlSample: 'https://demo-onionoo.internal/relays', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-013', name: 'EnterpriseAccess Demo Exchange', type: 'Synthetic Marketplace', reliability: 'A (High)', observationsCount: 38, firstIngested: '2025-03-18', lastIngested: '2026-09-20', urlSample: 'http://enterpriseaccessdemo88.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-014', name: 'CryptID Escrow Hub Feed', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 45, firstIngested: '2025-02-20', lastIngested: '2026-09-23', urlSample: 'http://cryptidescrowhubfeed.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-015', name: 'RansomPortal Demo Watch', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 41, firstIngested: '2025-04-01', lastIngested: '2026-09-25', urlSample: 'http://ransomportaldemowatch.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-016', name: 'MalShare Demo Corpus', type: 'Synthetic Intelligence Feed', reliability: 'B (Moderate)', observationsCount: 27, firstIngested: '2025-04-15', lastIngested: '2026-08-30', urlSample: 'https://demo-malshare.internal/samples', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-017', name: 'MixerPool Synthetic Telemetry', type: 'Synthetic Blockchain Cluster', reliability: 'B (Moderate)', observationsCount: 33, firstIngested: '2025-02-10', lastIngested: '2026-09-05', urlSample: 'https://demo-mixerpool.internal/traces', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-018', name: 'BeaconMarket Synthetic Catalog', type: 'Synthetic Marketplace', reliability: 'B (Moderate)', observationsCount: 24, firstIngested: '2025-03-25', lastIngested: '2026-08-28', urlSample: 'http://beaconmarketdemo99.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-019', name: 'Public Threat Report - Mandiant M-Trends Demo', type: 'Public Threat Report', reliability: 'A (High)', observationsCount: 16, firstIngested: '2025-06-01', lastIngested: '2026-04-15', urlSample: 'https://cloud.google.com/security/m-trends-synthetic-demo', isSynthetic: false, collectorMethod: 'Public Advisory Mirror' },
  { id: 'SOURCE-DEMO-020', name: 'Underground IRC Synthetic Logger', type: 'Synthetic Forum', reliability: 'C (Low)', observationsCount: 28, firstIngested: '2025-01-20', lastIngested: '2026-09-12', urlSample: 'irc://synthnet.onion/#underground', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  // Additional sources to reach 38
  { id: 'SOURCE-DEMO-021', name: 'Synthetic Jabber/XMPP Sniffer', type: 'Synthetic Forum', reliability: 'B (Moderate)', observationsCount: 22, firstIngested: '2025-02-14', lastIngested: '2026-08-25', urlSample: 'xmpp://synthjabber.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-022', name: 'DarkNet Escrow Ledger A', type: 'Synthetic Blockchain Cluster', reliability: 'A (High)', observationsCount: 31, firstIngested: '2025-03-05', lastIngested: '2026-09-20', urlSample: 'https://escrow-ledger-a.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-023', name: 'DarkNet Escrow Ledger B', type: 'Synthetic Blockchain Cluster', reliability: 'A (High)', observationsCount: 29, firstIngested: '2025-03-12', lastIngested: '2026-09-18', urlSample: 'https://escrow-ledger-b.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-024', name: 'Public Threat Report - TrendMicro Research Demo', type: 'Public Threat Report', reliability: 'A (High)', observationsCount: 14, firstIngested: '2025-07-01', lastIngested: '2026-03-20', urlSample: 'https://trendmicro.com/research/demo-cybercrime', isSynthetic: false, collectorMethod: 'Public Advisory Mirror' },
  { id: 'SOURCE-DEMO-025', name: 'Passive DNS Sensor East', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 35, firstIngested: '2025-01-02', lastIngested: '2026-09-24', urlSample: 'https://dns-sensor-east.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-026', name: 'Passive DNS Sensor West', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 33, firstIngested: '2025-01-04', lastIngested: '2026-09-24', urlSample: 'https://dns-sensor-west.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-027', name: 'ASN BGP Route Monitor', type: 'Synthetic Intelligence Feed', reliability: 'B (Moderate)', observationsCount: 20, firstIngested: '2025-02-18', lastIngested: '2026-08-15', urlSample: 'https://bgp-route-mon.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-028', name: 'Synthetic Ransomware Chat Mirror', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 40, firstIngested: '2025-04-10', lastIngested: '2026-09-22', urlSample: 'http://ransomchatsynth99.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-029', name: 'Synthetic Exploit DB Mirror', type: 'Synthetic Forum', reliability: 'A (High)', observationsCount: 26, firstIngested: '2025-02-28', lastIngested: '2026-09-14', urlSample: 'http://exploitdbsynth88.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-030', name: 'Telegram Synthetic Intelligence Channel A', type: 'Synthetic Forum', reliability: 'B (Moderate)', observationsCount: 34, firstIngested: '2025-05-01', lastIngested: '2026-09-19', urlSample: 'https://t.me/synth_threat_channel_a', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-031', name: 'Telegram Synthetic Intelligence Channel B', type: 'Synthetic Forum', reliability: 'C (Low)', observationsCount: 19, firstIngested: '2025-06-15', lastIngested: '2026-08-30', urlSample: 'https://t.me/synth_threat_channel_b', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-032', name: 'Synthetic Phish Feed Analyzer', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 37, firstIngested: '2025-03-22', lastIngested: '2026-09-21', urlSample: 'https://phishfeed-synth.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-033', name: 'Synthetic Stealer Log Aggregator', type: 'Synthetic Marketplace', reliability: 'A (High)', observationsCount: 43, firstIngested: '2025-01-28', lastIngested: '2026-09-23', urlSample: 'http://stealerlogaggregator99.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-034', name: 'Bulletproof Host Banner Probe', type: 'Synthetic Intelligence Feed', reliability: 'A (High)', observationsCount: 30, firstIngested: '2025-02-12', lastIngested: '2026-09-17', urlSample: 'https://bp-bannerprobe.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-035', name: 'Public Threat Report - Microsoft Security Signals Demo', type: 'Public Threat Report', reliability: 'A (High)', observationsCount: 17, firstIngested: '2025-08-01', lastIngested: '2026-05-10', urlSample: 'https://microsoft.com/security/blog/synthetic-demo', isSynthetic: false, collectorMethod: 'Public Advisory Mirror' },
  { id: 'SOURCE-DEMO-036', name: 'Underground Carding Portal Synthetic Log', type: 'Synthetic Marketplace', reliability: 'B (Moderate)', observationsCount: 25, firstIngested: '2025-08-14', lastIngested: '2026-07-22', urlSample: 'http://cardingsynth99portal.onion', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-037', name: 'DDoS Stresser Control Panel Sensor', type: 'Synthetic Intelligence Feed', reliability: 'B (Moderate)', observationsCount: 21, firstIngested: '2025-08-20', lastIngested: '2026-08-28', urlSample: 'http://stresserpanelsensor.internal', isSynthetic: true, collectorMethod: 'Synthetic Generator' },
  { id: 'SOURCE-DEMO-038', name: 'Academic Darknet Persona Corpus (Synthetic 2026)', type: 'Public Threat Report', reliability: 'A (High)', observationsCount: 52, firstIngested: '2025-01-01', lastIngested: '2026-09-26', urlSample: 'https://academic-darknet-deanonymization.org/corpus-2026', isSynthetic: true, collectorMethod: 'Synthetic Generator' }
];

export const SYNTHETIC_TIMELINE_EVENTS: TimelineEvent[] = [
  // ShadowX Key Events
  { id: 'EVT-001', actorId: 'ACTOR-DEMO-001', timestamp: '2025-02-14T09:20:00Z', eventType: 'Initial Observation', entity: 'ShadowX', source: 'Synthetic Forum Alpha', evidence: 'Account registration and initial introduction thread offering private database escrow credentials.', confidence: 95 },
  { id: 'EVT-002', actorId: 'ACTOR-DEMO-001', timestamp: '2025-03-02T14:15:00Z', eventType: 'PGP Key Discovered', entity: 'PGP-DEMO-001', source: 'Synthetic Forum Alpha', evidence: 'Actor appended public key 0x8A7C93F14E2B5A09 to profile signature with email shadow_sec@demomail.onion.', confidence: 98 },
  { id: 'EVT-003', actorId: 'ACTOR-DEMO-001', timestamp: '2025-04-19T18:40:00Z', eventType: 'Wallet Transaction', entity: 'WALLET-DEMO-001', source: 'Blockchain Cluster Synthetic Index', evidence: 'First incoming deposit of 3.42 BTC received from known underground tumbler address.', confidence: 92 },
  { id: 'EVT-004', actorId: 'ACTOR-DEMO-001', timestamp: '2025-07-11T11:05:00Z', eventType: 'Handle Registered', entity: 'Shadow_X01', source: 'Synthetic Market Omega', evidence: 'Vendor storefront created using identical stylometric sales template and identical PGP fingerprint.', confidence: 96 },
  { id: 'EVT-005', actorId: 'ACTOR-DEMO-001', timestamp: '2026-01-17T21:30:00Z', eventType: 'Infrastructure Associated', entity: 'demo-market-01.example', source: 'ThreatInfra Synthetic Telemetry', evidence: 'Domain DNS changed to IP 198.51.100.47, sharing custom nginx server banner with escrow portal.', confidence: 88 },
  { id: 'EVT-006', actorId: 'ACTOR-DEMO-001', timestamp: '2026-08-21T16:45:00Z', eventType: 'Marketplace Listing', entity: 'Shadow_X01', source: 'Synthetic Market Omega', evidence: 'Updated inventory listing 140 corporate VPN credentials with multi-sig escrow settlement.', confidence: 94 },

  // NightCipher Events
  { id: 'EVT-007', actorId: 'ACTOR-DEMO-002', timestamp: '2025-03-01T10:00:00Z', eventType: 'Initial Observation', entity: 'NightCipher', source: 'Synthetic Forum Alpha', evidence: 'First post announcing exfiltration proof-of-concept against regional healthcare provider.', confidence: 92 },
  { id: 'EVT-008', actorId: 'ACTOR-DEMO-002', timestamp: '2025-03-04T12:30:00Z', eventType: 'Infrastructure Associated', entity: 'demo-leak-portal-24.example', source: 'ThreatInfra Synthetic Telemetry', evidence: 'Host hosted on 198.51.100.52 (same /24 subnet as ShadowX marketplace infrastructure).', confidence: 78 },
  { id: 'EVT-009', actorId: 'ACTOR-DEMO-002', timestamp: '2025-05-18T15:20:00Z', eventType: 'Handle Registered', entity: 'CipherNight_24', source: 'LeakMarket Demo Archive', evidence: 'Created mirrored data extortion auction with linked proof files.', confidence: 90 },
  { id: 'EVT-010', actorId: 'ACTOR-DEMO-002', timestamp: '2026-08-14T19:10:00Z', eventType: 'Wallet Transaction', entity: 'WALLET-DEMO-002', source: 'Blockchain Cluster Synthetic Index', evidence: 'Ransom payment transfer of 12.5 BTC routed through intermediate hop.', confidence: 89 },

  // GhostByte Events
  { id: 'EVT-011', actorId: 'ACTOR-DEMO-003', timestamp: '2025-01-20T08:15:00Z', eventType: 'Initial Observation', entity: 'GhostByte', source: 'Synthetic Market Omega', evidence: 'Vendor launched high-volume crypto laundering liquidity pool.', confidence: 94 },
  { id: 'EVT-012', actorId: 'ACTOR-DEMO-003', timestamp: '2025-02-01T22:00:00Z', eventType: 'Wallet Transaction', entity: 'WALLET-DEMO-005', source: 'Blockchain Cluster Synthetic Index', evidence: 'Direct transaction cascade observed between WALLET-DEMO-001 (ShadowX) and WALLET-DEMO-005 (GhostByte).', confidence: 96 },
  { id: 'EVT-013', actorId: 'ACTOR-DEMO-003', timestamp: '2025-04-12T13:40:00Z', eventType: 'Handle Registered', entity: 'Ghost_B8', source: 'MixerPool Synthetic Telemetry', evidence: 'Operating administrative channel for mixer pool settlement.', confidence: 87 },
  { id: 'EVT-014', actorId: 'ACTOR-DEMO-003', timestamp: '2026-09-02T11:25:00Z', eventType: 'Wallet Transaction', entity: 'WALLET-DEMO-003', source: 'Blockchain Cluster Synthetic Index', evidence: 'Consolidated 245 ETH across 18 anonymous sub-wallets.', confidence: 91 },

  // Additional chronology for all 24 actors
  { id: 'EVT-015', actorId: 'ACTOR-DEMO-004', timestamp: '2025-04-10T16:00:00Z', eventType: 'Initial Observation', entity: 'DarkOrbit', source: 'Synthetic Forum Beta', evidence: 'Posted Python infostealer builder download links.', confidence: 90 },
  { id: 'EVT-016', actorId: 'ACTOR-DEMO-004', timestamp: '2025-04-12T17:30:00Z', eventType: 'Infrastructure Associated', entity: 'demo-payload-delivery-cdn.example', source: 'ThreatInfra Synthetic Telemetry', evidence: 'Delivery CDN registered on bulletproof Romanian host.', confidence: 85 },
  { id: 'EVT-017', actorId: 'ACTOR-DEMO-005', timestamp: '2025-05-18T10:15:00Z', eventType: 'Initial Observation', entity: 'RavenNode', source: 'Synthetic Forum Alpha', evidence: 'Offered domain admin credentials for Fortune 500 manufacturing conglomerate.', confidence: 95 },
  { id: 'EVT-018', actorId: 'ACTOR-DEMO-005', timestamp: '2025-05-20T14:40:00Z', eventType: 'Wallet Transaction', entity: 'WALLET-DEMO-007', source: 'Blockchain Cluster Synthetic Index', evidence: 'Received 8.2 BTC access brokerage fee into escrow.', confidence: 93 },
  { id: 'EVT-019', actorId: 'ACTOR-DEMO-006', timestamp: '2025-06-01T09:00:00Z', eventType: 'Initial Observation', entity: 'ZeroTrace', source: 'OnionDrop Demo Paste', evidence: 'Published isolated advisory on kernel vulnerabilities under zero metadata trail.', confidence: 75 },
  { id: 'EVT-020', actorId: 'ACTOR-DEMO-007', timestamp: '2025-02-28T18:10:00Z', eventType: 'Initial Observation', entity: 'PhantomRoot', source: 'Synthetic Forum Beta', evidence: 'Demonstrated Linux eBPF rootkit bypass in technical sub-board.', confidence: 88 },
  { id: 'EVT-021', actorId: 'ACTOR-DEMO-008', timestamp: '2025-07-04T12:00:00Z', eventType: 'Initial Observation', entity: 'SilentVector', source: 'Synthetic Market Omega', evidence: 'Listed fast-flux bulletproof DNS proxy leasing plans.', confidence: 92 },
  { id: 'EVT-022', actorId: 'ACTOR-DEMO-009', timestamp: '2025-03-15T15:30:00Z', eventType: 'Initial Observation', entity: 'CobaltWeaver', source: 'Synthetic Forum Alpha', evidence: 'Advertised customized Cobalt Strike malleable profiles with evasion metrics.', confidence: 94 },
  { id: 'EVT-023', actorId: 'ACTOR-DEMO-010', timestamp: '2025-08-11T14:20:00Z', eventType: 'Initial Observation', entity: 'KryptonGhost', source: 'Synthetic Market Omega', evidence: 'Published automated bin-checking and stolen card validation API.', confidence: 86 },
  { id: 'EVT-024', actorId: 'ACTOR-DEMO-011', timestamp: '2025-04-22T09:45:00Z', eventType: 'Initial Observation', entity: 'ViperLoom', source: 'Synthetic Forum Alpha', evidence: 'Negotiated high-profile double extortion victim communications on behalf of ransomware group.', confidence: 97 },
  { id: 'EVT-025', actorId: 'ACTOR-DEMO-012', timestamp: '2025-05-09T11:15:00Z', eventType: 'Initial Observation', entity: 'OnyxReaper', source: 'LeakMarket Demo Archive', evidence: 'Published 400GB proprietary CAD schematic dump from aviation vendor.', confidence: 89 },
  { id: 'EVT-026', actorId: 'ACTOR-DEMO-013', timestamp: '2025-09-01T20:00:00Z', eventType: 'Initial Observation', entity: 'AegisNull', source: 'Synthetic Forum Beta', evidence: 'Detailed multi-layer Tor over VPN protocol tests.', confidence: 80 },
  { id: 'EVT-027', actorId: 'ACTOR-DEMO-014', timestamp: '2025-06-17T13:30:00Z', eventType: 'Initial Observation', entity: 'FrostByte', source: 'BotMaster Demo Network', evidence: 'Managed distribution loader campaigns spreading modular backdoors.', confidence: 87 },
  { id: 'EVT-028', actorId: 'ACTOR-DEMO-015', timestamp: '2025-01-15T10:10:00Z', eventType: 'Initial Observation', entity: 'IronSpecter', source: 'Synthetic Forum Alpha', evidence: 'Offered cloud SSO session cookie replay attack toolkits.', confidence: 95 },
  { id: 'EVT-029', actorId: 'ACTOR-DEMO-016', timestamp: '2025-07-21T16:50:00Z', eventType: 'Initial Observation', entity: 'NexusDrift', source: 'Synthetic Market Omega', evidence: 'Distributed synthetic identity packages with matching credit histories.', confidence: 85 },
  { id: 'EVT-030', actorId: 'ACTOR-DEMO-017', timestamp: '2025-08-04T18:25:00Z', eventType: 'Initial Observation', entity: 'PulseFiend', source: 'Synthetic Forum Beta', evidence: 'Advertised 800Gbps SYN flood booter stresser rentals.', confidence: 82 },
  { id: 'EVT-031', actorId: 'ACTOR-DEMO-018', timestamp: '2025-03-12T14:00:00Z', eventType: 'Initial Observation', entity: 'CrimsonHelix', source: 'Synthetic Forum Alpha', evidence: 'Managed payload encryption key testing suites for ransomware affiliates.', confidence: 96 },
  { id: 'EVT-032', actorId: 'ACTOR-DEMO-019', timestamp: '2025-10-05T21:15:00Z', eventType: 'Initial Observation', entity: 'VoidStrider', source: 'Synthetic Forum Beta', evidence: 'Published cryptographic review of custom underground forum tokens.', confidence: 79 },
  { id: 'EVT-033', actorId: 'ACTOR-DEMO-020', timestamp: '2025-02-18T11:40:00Z', eventType: 'Initial Observation', entity: 'TitanForge', source: 'Synthetic Forum Alpha', evidence: 'Brokered unauthenticated RCE exploit proof-of-concept for enterprise firewall.', confidence: 98 },
  { id: 'EVT-034', actorId: 'ACTOR-DEMO-021', timestamp: '2025-06-29T17:10:00Z', eventType: 'Initial Observation', entity: 'EchoBane', source: 'LeakMarket Demo Archive', evidence: 'Indexed multi-breach archive lookup API for subterranean investigators.', confidence: 84 },
  { id: 'EVT-035', actorId: 'ACTOR-DEMO-022', timestamp: '2025-05-30T15:45:00Z', eventType: 'Initial Observation', entity: 'SolarFlare_X', source: 'Synthetic Market Omega', evidence: 'Automated TDS redirecting targeted geographic banking visitors.', confidence: 86 },
  { id: 'EVT-036', actorId: 'ACTOR-DEMO-023', timestamp: '2025-07-19T19:30:00Z', eventType: 'Initial Observation', entity: 'NebulaShroud', source: 'Synthetic Forum Beta', evidence: 'Sold seed lists for resilient domain generation algorithms.', confidence: 81 },
  { id: 'EVT-037', actorId: 'ACTOR-DEMO-024', timestamp: '2025-04-03T09:15:00Z', eventType: 'Initial Observation', entity: 'QuasarLock', source: 'Synthetic Forum Alpha', evidence: 'Launched automated extortion ticket support portal with multi-sig settlement.', confidence: 95 },

  // Secondary timeline events covering 2025-2026 chronological investigation
  { id: 'EVT-038', actorId: 'ACTOR-DEMO-001', timestamp: '2025-09-03T11:20:00Z', eventType: 'Handle Registered', entity: 'XShadow', source: 'CryptID Escrow Hub Feed', evidence: 'Linked alternate handle XShadow with same PGP key fingerprint 9B42 81E3...', confidence: 96 },
  { id: 'EVT-039', actorId: 'ACTOR-DEMO-001', timestamp: '2025-11-12T14:45:00Z', eventType: 'Forum Posting', entity: 'ShadowOperator', source: 'Synthetic Forum Beta', evidence: 'Inquired regarding bulletproof hosting providers located in Netherlands and Switzerland.', confidence: 85 },
  { id: 'EVT-040', actorId: 'ACTOR-DEMO-001', timestamp: '2026-03-10T16:15:00Z', eventType: 'Wallet Transaction', entity: 'WALLET-DEMO-004', source: 'Blockchain Cluster Synthetic Index', evidence: 'Withdrew 450 XMR from marketplace escrow pool to private obfuscated wallet.', confidence: 89 },
  { id: 'EVT-041', actorId: 'ACTOR-DEMO-001', timestamp: '2026-05-24T18:30:00Z', eventType: 'Infrastructure Associated', entity: 'shadowx47escrow7kldemomarket.onion', source: 'Synthetic Forum Alpha', evidence: 'Published dedicated Tor onion landing page for private tier buyers.', confidence: 97 },
  { id: 'EVT-042', actorId: 'ACTOR-DEMO-002', timestamp: '2025-08-04T12:00:00Z', eventType: 'Forum Posting', entity: 'NC_Dev', source: 'CryptID Escrow Hub Feed', evidence: 'Discussed joint revenue sharing model with high-volume access brokers.', confidence: 84 },
  { id: 'EVT-043', actorId: 'ACTOR-DEMO-003', timestamp: '2025-09-15T15:10:00Z', eventType: 'Forum Posting', entity: 'ByteGhost99', source: 'Synthetic Forum Alpha', evidence: 'Advertised zero-slippage Monero-to-Bitcoin cross-chain swaps.', confidence: 92 },
  { id: 'EVT-044', actorId: 'ACTOR-DEMO-005', timestamp: '2025-07-09T10:45:00Z', eventType: 'Marketplace Listing', entity: 'Raven_Ops', source: 'EnterpriseAccess Demo Exchange', evidence: 'Sold active corporate VPN profile for Scandinavian transport operator.', confidence: 94 },
  { id: 'EVT-045', actorId: 'ACTOR-DEMO-009', timestamp: '2025-05-20T17:20:00Z', eventType: 'Marketplace Listing', entity: 'CW_Strike', source: 'BeaconMarket Synthetic Catalog', evidence: 'Delivered customized CS malleable beacon with signed DLL sideloading loader.', confidence: 96 },
  { id: 'EVT-046', actorId: 'ACTOR-DEMO-011', timestamp: '2025-06-15T13:40:00Z', eventType: 'Infrastructure Associated', entity: 'viperloomsupportextortportal.onion', source: 'RansomPortal Demo Watch', evidence: 'Deployed live darknet extortion negotiation portal for victims.', confidence: 98 },
  { id: 'EVT-047', actorId: 'ACTOR-DEMO-015', timestamp: '2025-04-05T11:30:00Z', eventType: 'Marketplace Listing', entity: 'SpecterIron', source: 'EnterpriseAccess Demo Exchange', evidence: 'Auctioned 500 active Okta and Entra ID session cookies.', confidence: 93 },
  { id: 'EVT-048', actorId: 'ACTOR-DEMO-018', timestamp: '2025-05-28T16:15:00Z', eventType: 'Infrastructure Associated', entity: 'crimsonhelixdecryptersite99.onion', source: 'Synthetic Forum Alpha', evidence: 'Automated test-decrypt portal validated 10 demo encrypted files.', confidence: 97 },
  { id: 'EVT-049', actorId: 'ACTOR-DEMO-020', timestamp: '2025-05-11T14:50:00Z', eventType: 'Forum Posting', entity: 'TF_Exploit', source: 'EnterpriseAccess Demo Exchange', evidence: 'Published weaponized proof-of-concept for CVE-2025-DEMO-9912.', confidence: 98 },
  { id: 'EVT-050', actorId: 'ACTOR-DEMO-024', timestamp: '2025-07-14T10:20:00Z', eventType: 'Marketplace Listing', entity: 'LockQuasar', source: 'RansomPortal Demo Watch', evidence: 'Integrated multi-tier affiliate revenue split calculator.', confidence: 95 }
];

export const SYNTHETIC_RELATIONSHIPS: RelationshipRecord[] = [
  // ShadowX Central Relationships
  { id: 'REL-001', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'HDL-001', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 100, firstObserved: '2025-02-14', lastObserved: '2026-08-21', evidenceSummary: 'Primary observed handle across underground forums.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-002', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'HDL-002', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 94, firstObserved: '2025-07-11', lastObserved: '2026-08-19', evidenceSummary: 'Secondary vendor persona on Synthetic Market Omega.', sourceId: 'SOURCE-DEMO-002' },
  { id: 'REL-003', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'HDL-003', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 90, firstObserved: '2025-09-03', lastObserved: '2026-07-28', evidenceSummary: 'Escrow account linked through verified PGP signature.', sourceId: 'SOURCE-DEMO-014' },
  { id: 'REL-004', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'PGP-DEMO-001', targetNodeType: 'PGPKey', relationshipType: 'USES', confidenceScore: 98, firstObserved: '2025-01-10', lastObserved: '2026-08-21', evidenceSummary: 'Key fingerprint 9B42 81E3... present in forum profile signature and escrow contracts.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-005', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'WALLET-DEMO-001', targetNodeType: 'Wallet', relationshipType: 'USES', confidenceScore: 92, firstObserved: '2025-02-16', lastObserved: '2026-08-20', evidenceSummary: 'Primary Bitcoin settlement wallet provided for private deals.', sourceId: 'SOURCE-DEMO-007' },
  { id: 'REL-006', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'WALLET-DEMO-004', targetNodeType: 'Wallet', relationshipType: 'USES', confidenceScore: 89, firstObserved: '2025-04-19', lastObserved: '2026-07-29', evidenceSummary: 'Private Monero address utilized for untraceable commission payouts.', sourceId: 'SOURCE-DEMO-007' },
  { id: 'REL-007', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'INFRA-DEMO-001', targetNodeType: 'Infrastructure', relationshipType: 'ASSOCIATED_WITH', confidenceScore: 88, firstObserved: '2025-02-14', lastObserved: '2026-08-21', evidenceSummary: 'Direct DNS correlation to vendor marketplace frontend.', sourceId: 'SOURCE-DEMO-008' },
  { id: 'REL-008', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'INFRA-DEMO-004', targetNodeType: 'Infrastructure', relationshipType: 'ASSOCIATED_WITH', confidenceScore: 96, firstObserved: '2025-03-01', lastObserved: '2026-08-19', evidenceSummary: 'Tor onion service published directly by ShadowX in forum introduction.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-009', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'SOURCE-DEMO-001', targetNodeType: 'Source', relationshipType: 'SEEN_ON', confidenceScore: 95, firstObserved: '2025-02-14', lastObserved: '2026-08-21', evidenceSummary: 'Frequent activity, 142 total recorded posts.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-010', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'SOURCE-DEMO-002', targetNodeType: 'Source', relationshipType: 'SEEN_ON', confidenceScore: 94, firstObserved: '2025-07-11', lastObserved: '2026-08-19', evidenceSummary: 'Active vendor status, 88 marketplace transactions.', sourceId: 'SOURCE-DEMO-002' },

  // Correlating ShadowX with NightCipher (Shared Infrastructure INFRA-DEMO-001 & INFRA-DEMO-002)
  { id: 'REL-011', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'ACTOR-DEMO-002', targetNodeType: 'Actor', relationshipType: 'CONNECTED_TO', confidenceScore: 68, firstObserved: '2025-03-04', lastObserved: '2026-08-14', evidenceSummary: 'Shared /24 hosting subnet, identical custom hardened nginx banner, and mutual forum endorsements.', sourceId: 'SOURCE-DEMO-008' },
  { id: 'REL-012', sourceNodeId: 'ACTOR-DEMO-002', sourceNodeType: 'Actor', targetNodeId: 'INFRA-DEMO-001', targetNodeType: 'Infrastructure', relationshipType: 'ASSOCIATED_WITH', confidenceScore: 74, firstObserved: '2025-03-04', lastObserved: '2026-08-14', evidenceSummary: 'Resolved to the same hosting IP 198.51.100.47 during March-May 2025.', sourceId: 'SOURCE-DEMO-008' },
  { id: 'REL-013', sourceNodeId: 'ACTOR-DEMO-002', sourceNodeType: 'Actor', targetNodeId: 'PGP-DEMO-004', targetNodeType: 'PGPKey', relationshipType: 'USES', confidenceScore: 95, firstObserved: '2025-02-25', lastObserved: '2026-08-14', evidenceSummary: 'Key fingerprint 810A 32E9... utilized for extortion victim verification.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-014', sourceNodeId: 'ACTOR-DEMO-002', sourceNodeType: 'Actor', targetNodeId: 'WALLET-DEMO-002', targetNodeType: 'Wallet', relationshipType: 'USES', confidenceScore: 91, firstObserved: '2025-03-05', lastObserved: '2026-08-12', evidenceSummary: 'Extortion fee collection wallet.', sourceId: 'SOURCE-DEMO-007' },

  // Correlating ShadowX with GhostByte (Shared Financial Wallet Cluster WALLET-DEMO-001 -> WALLET-DEMO-005)
  { id: 'REL-015', sourceNodeId: 'ACTOR-DEMO-001', sourceNodeType: 'Actor', targetNodeId: 'ACTOR-DEMO-003', targetNodeType: 'Actor', relationshipType: 'LINKED_TO', confidenceScore: 79, firstObserved: '2025-02-01', lastObserved: '2026-08-25', evidenceSummary: 'Strong financial cluster link: 18 direct transaction hops between ShadowX wallet and GhostByte mixer pool.', sourceId: 'SOURCE-DEMO-007' },
  { id: 'REL-016', sourceNodeId: 'ACTOR-DEMO-003', sourceNodeType: 'Actor', targetNodeId: 'WALLET-DEMO-001', targetNodeType: 'Wallet', relationshipType: 'CONNECTED_TO', confidenceScore: 84, firstObserved: '2025-02-01', lastObserved: '2026-08-25', evidenceSummary: 'Multi-sig co-signer identified on 4 mixer settlement transactions.', sourceId: 'SOURCE-DEMO-007' },
  { id: 'REL-017', sourceNodeId: 'ACTOR-DEMO-003', sourceNodeType: 'Actor', targetNodeId: 'PGP-DEMO-003', targetNodeType: 'PGPKey', relationshipType: 'USES', confidenceScore: 97, firstObserved: '2025-01-18', lastObserved: '2026-09-02', evidenceSummary: 'PGP Key 0x992FE80112BA47C2.', sourceId: 'SOURCE-DEMO-002' },
  { id: 'REL-018', sourceNodeId: 'ACTOR-DEMO-003', sourceNodeType: 'Actor', targetNodeId: 'INFRA-DEMO-007', targetNodeType: 'Infrastructure', relationshipType: 'ASSOCIATED_WITH', confidenceScore: 91, firstObserved: '2025-01-25', lastObserved: '2026-09-02', evidenceSummary: 'Mixer relay node in Switzerland.', sourceId: 'SOURCE-DEMO-008' },

  // Linking handles to each other
  { id: 'REL-019', sourceNodeId: 'HDL-001', sourceNodeType: 'Handle', targetNodeId: 'HDL-002', targetNodeType: 'Handle', relationshipType: 'SAME_IDENTIFIER', confidenceScore: 93, firstObserved: '2025-07-11', lastObserved: '2026-08-21', evidenceSummary: 'Shared PGP key 0x8A7C93F14E2B5A09, matching payment addresses, and 91% stylometric similarity.', sourceId: 'SOURCE-DEMO-038' },
  { id: 'REL-020', sourceNodeId: 'HDL-001', sourceNodeType: 'Handle', targetNodeId: 'HDL-003', targetNodeType: 'Handle', relationshipType: 'SAME_IDENTIFIER', confidenceScore: 89, firstObserved: '2025-09-03', lastObserved: '2026-07-28', evidenceSummary: 'Identical PGP key fingerprint and co-occurring activity hours.', sourceId: 'SOURCE-DEMO-038' },

  // RavenNode (ACTOR-DEMO-005) relationships
  { id: 'REL-021', sourceNodeId: 'ACTOR-DEMO-005', sourceNodeType: 'Actor', targetNodeId: 'HDL-014', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 100, firstObserved: '2025-05-18', lastObserved: '2026-09-12', evidenceSummary: 'Primary handle RavenNode.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-022', sourceNodeId: 'ACTOR-DEMO-005', sourceNodeType: 'Actor', targetNodeId: 'PGP-DEMO-005', targetNodeType: 'PGPKey', relationshipType: 'USES', confidenceScore: 98, firstObserved: '2025-05-10', lastObserved: '2026-09-12', evidenceSummary: 'PGP Key 0x17DEB99204A8F31C.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-023', sourceNodeId: 'ACTOR-DEMO-005', sourceNodeType: 'Actor', targetNodeId: 'WALLET-DEMO-007', targetNodeType: 'Wallet', relationshipType: 'USES', confidenceScore: 94, firstObserved: '2025-05-20', lastObserved: '2026-09-10', evidenceSummary: 'Access broker escrow wallet.', sourceId: 'SOURCE-DEMO-007' },
  { id: 'REL-024', sourceNodeId: 'ACTOR-DEMO-005', sourceNodeType: 'Actor', targetNodeId: 'ACTOR-DEMO-001', targetNodeType: 'Actor', relationshipType: 'CONNECTED_TO', confidenceScore: 72, firstObserved: '2025-06-15', lastObserved: '2026-08-10', evidenceSummary: 'Repeated bulk trade of corporate VPN access between RavenNode and ShadowX.', sourceId: 'SOURCE-DEMO-001' },

  // CobaltWeaver (ACTOR-DEMO-009) relationships
  { id: 'REL-025', sourceNodeId: 'ACTOR-DEMO-009', sourceNodeType: 'Actor', targetNodeId: 'HDL-026', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 100, firstObserved: '2025-03-15', lastObserved: '2026-08-29', evidenceSummary: 'Primary handle CobaltWeaver.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-026', sourceNodeId: 'ACTOR-DEMO-009', sourceNodeType: 'Actor', targetNodeId: 'PGP-DEMO-008', targetNodeType: 'PGPKey', relationshipType: 'USES', confidenceScore: 96, firstObserved: '2025-03-08', lastObserved: '2026-08-29', evidenceSummary: 'PGP Key 0x0984DF112C77BA88.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-027', sourceNodeId: 'ACTOR-DEMO-009', sourceNodeType: 'Actor', targetNodeId: 'INFRA-DEMO-017', targetNodeType: 'Infrastructure', relationshipType: 'ASSOCIATED_WITH', confidenceScore: 92, firstObserved: '2025-03-20', lastObserved: '2026-08-29', evidenceSummary: 'C2 beacon server.', sourceId: 'SOURCE-DEMO-008' },
  { id: 'REL-028', sourceNodeId: 'ACTOR-DEMO-009', sourceNodeType: 'Actor', targetNodeId: 'ACTOR-DEMO-011', targetNodeType: 'Actor', relationshipType: 'LINKED_TO', confidenceScore: 82, firstObserved: '2025-04-25', lastObserved: '2026-08-20', evidenceSummary: 'CobaltWeaver malleable profiles observed in ViperLoom ransomware intrusion campaigns.', sourceId: 'SOURCE-DEMO-010' },

  // ViperLoom (ACTOR-DEMO-011) relationships
  { id: 'REL-029', sourceNodeId: 'ACTOR-DEMO-011', sourceNodeType: 'Actor', targetNodeId: 'HDL-032', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 100, firstObserved: '2025-04-22', lastObserved: '2026-09-08', evidenceSummary: 'Primary negotiator persona.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-030', sourceNodeId: 'ACTOR-DEMO-011', sourceNodeType: 'Actor', targetNodeId: 'PGP-DEMO-009', targetNodeType: 'PGPKey', relationshipType: 'USES', confidenceScore: 97, firstObserved: '2025-04-14', lastObserved: '2026-09-08', evidenceSummary: 'PGP Key 0x44B192A0FE18DC52.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-031', sourceNodeId: 'ACTOR-DEMO-011', sourceNodeType: 'Actor', targetNodeId: 'WALLET-DEMO-013', targetNodeType: 'Wallet', relationshipType: 'USES', confidenceScore: 95, firstObserved: '2025-04-26', lastObserved: '2026-09-06', evidenceSummary: 'Ransom payment wallet.', sourceId: 'SOURCE-DEMO-007' },
  { id: 'REL-032', sourceNodeId: 'ACTOR-DEMO-011', sourceNodeType: 'Actor', targetNodeId: 'ACTOR-DEMO-018', targetNodeType: 'Actor', relationshipType: 'CONNECTED_TO', confidenceScore: 86, firstObserved: '2025-05-10', lastObserved: '2026-09-05', evidenceSummary: 'Shared extortion portal architecture with CrimsonHelix.', sourceId: 'SOURCE-DEMO-015' },

  // TitanForge (ACTOR-DEMO-020) relationships
  { id: 'REL-033', sourceNodeId: 'ACTOR-DEMO-020', sourceNodeType: 'Actor', targetNodeId: 'HDL-059', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 100, firstObserved: '2025-02-18', lastObserved: '2026-09-22', evidenceSummary: 'Primary handle TitanForge.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-034', sourceNodeId: 'ACTOR-DEMO-020', sourceNodeType: 'Actor', targetNodeId: 'PGP-DEMO-013', targetNodeType: 'PGPKey', relationshipType: 'USES', confidenceScore: 99, firstObserved: '2025-02-10', lastObserved: '2026-09-22', evidenceSummary: 'PGP Key 0x12BA44FE990188C7.', sourceId: 'SOURCE-DEMO-001' },
  { id: 'REL-035', sourceNodeId: 'ACTOR-DEMO-020', sourceNodeType: 'Actor', targetNodeId: 'INFRA-DEMO-031', targetNodeType: 'Infrastructure', relationshipType: 'ASSOCIATED_WITH', confidenceScore: 93, firstObserved: '2025-02-25', lastObserved: '2026-09-22', evidenceSummary: 'Exploit demo server hosted on same AS64501 network as ShadowX.', sourceId: 'SOURCE-DEMO-008' },
  { id: 'REL-036', sourceNodeId: 'ACTOR-DEMO-020', sourceNodeType: 'Actor', targetNodeId: 'ACTOR-DEMO-001', targetNodeType: 'Actor', relationshipType: 'CONNECTED_TO', confidenceScore: 66, firstObserved: '2025-03-10', lastObserved: '2026-07-15', evidenceSummary: 'Observed purchasing custom credential stuffing exploits from TitanForge.', sourceId: 'SOURCE-DEMO-001' },

  // Negative Control: ZeroTrace has NO links to ShadowX
  { id: 'REL-037', sourceNodeId: 'ACTOR-DEMO-006', sourceNodeType: 'Actor', targetNodeId: 'HDL-017', targetNodeType: 'Handle', relationshipType: 'USES', confidenceScore: 100, firstObserved: '2025-06-01', lastObserved: '2026-08-05', evidenceSummary: 'Primary handle ZeroTrace.', sourceId: 'SOURCE-DEMO-006' },
  { id: 'REL-038', sourceNodeId: 'ACTOR-DEMO-006', sourceNodeType: 'Actor', targetNodeId: 'WALLET-DEMO-008', targetNodeType: 'Wallet', relationshipType: 'USES', confidenceScore: 85, firstObserved: '2025-06-08', lastObserved: '2026-07-20', evidenceSummary: 'Isolated Monero address.', sourceId: 'SOURCE-DEMO-007' }
];

export const SYNTHETIC_OBSERVATIONS: ObservationRecord[] = [
  { id: 'OBS-001', actorId: 'ACTOR-DEMO-001', entityType: 'Actor', entityValue: 'ShadowX', sourceId: 'SOURCE-DEMO-001', timestamp: '2025-02-14T09:20:00Z', eventDescription: 'Observed registered member introduction on Synthetic Forum Alpha.', rawSampleSnippet: 'Hello board, offering verified corporate SSO credentials. Escrow via PGP only.', confidenceScore: 95 },
  { id: 'OBS-002', actorId: 'ACTOR-DEMO-001', entityType: 'PGPKey', entityValue: 'PGP-DEMO-001', sourceId: 'SOURCE-DEMO-001', timestamp: '2025-03-02T14:15:00Z', eventDescription: 'PGP public key 0x8A7C93F14E2B5A09 signed message captured.', rawSampleSnippet: '-----BEGIN PGP PUBLIC KEY BLOCK-----\nmQINBGZ...ShadowX Security<shadow_sec@demomail.onion>', confidenceScore: 99 },
  { id: 'OBS-003', actorId: 'ACTOR-DEMO-001', entityType: 'Wallet', entityValue: 'WALLET-DEMO-001', sourceId: 'SOURCE-DEMO-007', timestamp: '2025-04-19T18:40:00Z', eventDescription: 'Incoming payment of 3.42 BTC to address bc1q9v8t7z...', rawSampleSnippet: 'TXID: 88f2a1b9... 3.42 BTC -> bc1q9v8t7z6y5x4w3v2u1t0s9r8q7p6o5n4m3l2k1j', confidenceScore: 92 },
  { id: 'OBS-004', actorId: 'ACTOR-DEMO-001', entityType: 'Handle', entityValue: 'Shadow_X01', sourceId: 'SOURCE-DEMO-002', timestamp: '2025-07-11T11:05:00Z', eventDescription: 'Vendor listing on Synthetic Market Omega published under Shadow_X01.', rawSampleSnippet: 'Corporate VPN Access Pack - Delivery within 10 min. Settlement via escrow.', confidenceScore: 96 },
  { id: 'OBS-005', actorId: 'ACTOR-DEMO-001', entityType: 'Infrastructure', entityValue: 'INFRA-DEMO-001', sourceId: 'SOURCE-DEMO-008', timestamp: '2026-01-17T21:30:00Z', eventDescription: 'Domain demo-market-01.example active on IP 198.51.100.47.', rawSampleSnippet: 'A demo-market-01.example -> 198.51.100.47 (AS64501 DEMO-HOST, NL)', confidenceScore: 91 },
  { id: 'OBS-006', actorId: 'ACTOR-DEMO-002', entityType: 'Actor', entityValue: 'NightCipher', sourceId: 'SOURCE-DEMO-001', timestamp: '2025-03-01T10:00:00Z', eventDescription: 'Extortion proof published on Synthetic Forum Alpha.', rawSampleSnippet: 'Hospital medical records archive preview available. Proof samples attached.', confidenceScore: 90 },
  { id: 'OBS-007', actorId: 'ACTOR-DEMO-003', entityType: 'Wallet', entityValue: 'WALLET-DEMO-003', sourceId: 'SOURCE-DEMO-007', timestamp: '2025-01-22T08:15:00Z', eventDescription: 'High-volume smart contract deposits routed through mixer.', rawSampleSnippet: 'Cluster 0x71C0aB9D... handled 215 unique txs across 14 darknet pools.', confidenceScore: 94 },
  { id: 'OBS-008', actorId: 'ACTOR-DEMO-005', entityType: 'Handle', entityValue: 'RavenNode', sourceId: 'SOURCE-DEMO-001', timestamp: '2025-05-18T10:15:00Z', eventDescription: 'Active enterprise access auction initiated.', rawSampleSnippet: 'RDP & VPN Enterprise perimeter access - Fortune 500 domain.', confidenceScore: 95 }
];
